const NODES = [
  {
    id: "index",
    t: "Beranda",
    i: "🏠",
    d: "Gerbang utama",
    x: 210,
    y: 35,
    to: ["profil", "falsafah", "motif", "audio", "peta", "graf"],
  },
  {
    id: "profil",
    t: "Profil",
    i: "👥",
    d: "Siapa Suku Boti",
    x: 60,
    y: 115,
    to: ["falsafah", "peta"],
  },
  {
    id: "falsafah",
    t: "Falsafah",
    i: "🌿",
    d: "Nilai hidup & adat",
    x: 130,
    y: 205,
    to: ["motif", "profil"],
  },
  {
    id: "motif",
    t: "Motif",
    i: "🧵",
    d: "Galeri tenun alami",
    x: 290,
    y: 205,
    to: ["audio", "falsafah"],
  },
  {
    id: "audio",
    t: "Audio",
    i: "🔊",
    d: "TTS & bahasa lokal",
    x: 360,
    y: 115,
    to: ["peta", "profil"],
  },
  {
    id: "peta",
    t: "Peta",
    i: "📍",
    d: "Lokasi interaktif",
    x: 210,
    y: 285,
    to: ["profil", "motif"],
  },
  {
    id: "graf",
    t: "Graf",
    i: "🕸️",
    d: "Struktur hypermedia",
    x: 40,
    y: 290,
    to: ["index"],
  },
  {
    id: "tugas",
    t: "Tugas PDF",
    i: "📄",
    d: "Buka laporan (PDF)",
    x: 380,
    y: 290,
    to: ["index"],
    s: 1,
    h: "assets/laporan.pdf",
  },
];
